---
name: Build Docker Image

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          cd node
          docker build -t temp/build .
          
      - name: Push Docker Image
        run: |
         echo ${{ secrets.PASSWORD }} | docker login --username ${{ secrets.USERNAME }} --password-stdin
         docker tag temp/build farisadlin/hello-world:latest
         docker tag temp/build farisadlin/hello-world:${{ github.sha }}
         docker push farisadlin/hello-world:latest
         docker push farisadlin/hello-world:${{ github.sha }}
