---
name: Run Unit Tests

on: 
  push:
    branches:
    - master

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: ./.github/actions/build.yaml
        
      - name: yarn test
        run: |
         yarn test
        env:
         CI: true

      - name: docker build
        run: |
          docker build -t temp/build .
          
      - name: Push docker image
        run: |
         docker tag temp/build hello-world:latest
         docker tag temp/build hello-world:${{ github.sha }}
         docker push hello-world:latest
         docker push hello-world:${{ github.sha }}
