---
name: Build Docker Image

on: 
  push:
    branches:
    - master

jobs:
  deploy:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: yarn install
        run: | 
          yarn install

      - name: docker build
        run: |
          docker build -t temp/build .
          
      - name: Push docker image
        run: |
         docker tag temp/build farisadlin/hello-world:latest
         docker tag temp/build farisadlin/hello-world:${{ github.sha }}
         docker push farisadlin/hello-world:latest
         docker push farisadlin/hello-world:${{ github.sha }}
